// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function twoFer(input) {
  if (input !== undefined) {
    return "One for " + (input + ", one for me.");
  } else {
    return "One for you, one for me.";
  }
}

exports.twoFer = twoFer;
/* No side effect */
